### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by adameus03** [adameus03/uart_cam_driver#1]
- [x] Out-of-box support for multiple connected devices (Done, but ...
- [ ] ...the program could be made to detect device connection/disconnection and manage multiple sessions authomatically instead of requiring manual launch of separate processes with appropriate arguments for each connected device (`ucd /dev/ttyUSB0 0`, `ucd /dev/ttyUSB1 1`, etc.))
- [ ] LED control
- [ ] Handle multiple client processes
